// app/(site)/about/page.tsx
import type { Metadata } from "next";
import {
  Container,
  Heading,
  Link,
  Section,
  SectionContainer,
} from "@/design/base";
import styles from "./page.module.css";

export const metadata: Metadata = {
  metadataBase: new URL("https://tyankatsu.com"),
  title: "About - tyankatsu.com",
  description: "著者紹介ページです。",
};

export default async function About() {
  return (
    <Container>
      <Heading>About</Heading>

      <SectionContainer>
        <Section title="Work">
          <ul className={styles.section__list}>
            <li className={styles["section__list-item"]}>
              Front-end Engineer: Linc&apos;well - (December 2022 - Present)
            </li>
            <li className={styles["section__list-item"]}>
              Front-end Engineer: HRBrain - (July 2020 - October 2022)
            </li>
            <li className={styles["section__list-item"]}>
              Front-end Engineer: VEGA corporation - (July 2018 - June 2020)
            </li>
            <li className={styles["section__list-item"]}>
              Web Designer: Japanese company - (2016 - June 2018)
            </li>
          </ul>
        </Section>

        <Section title="Internet">
          <ul className={styles.section__list}>
            <li className={styles["section__list-item"]}>
              <Link
                href="https://x.com/tyankatsu5"
                target="_blank"
                className={styles["section__list-item-link"]}
              >
                X
              </Link>
            </li>
            <li className={styles["section__list-item"]}>
              <Link
                href="https://github.com/tyankatsu0105"
                target="_blank"
                className={styles["section__list-item-link"]}
              >
                GitHub
              </Link>
            </li>
            <li className={styles["section__list-item"]}>
              <Link
                href="https://www.npmjs.com/~tyankatsu0105"
                target="_blank"
                className={styles["section__list-item-link"]}
              >
                npm
              </Link>
            </li>
            <li className={styles["section__list-item"]}>
              <Link
                href="https://speakerdeck.com/tyankatsu"
                target="_blank"
                className={styles["section__list-item-link"]}
              >
                Speaker Deck
              </Link>
            </li>
            <li className={styles["section__list-item"]}>
              <Link
                href="https://katsulog.netlify.app/"
                target="_blank"
                className={styles["section__list-item-link"]}
              >
                katsulog
              </Link>
            </li>
          </ul>
        </Section>

        <Section title="Book">
          <ul className={styles.section__list}>
            <li className={styles["section__list-item"]}>
              <Link
                href="https://ponday.booth.pm/items/1316963"
                target="_blank"
                className={styles["section__list-item-link"]}
              >
                チームマネジメントとGridsome／VuePress
              </Link>
            </li>
          </ul>
        </Section>

        <Section title="Community">
          <ul className={styles.section__list}>
            <li className={styles["section__list-item"]}>
              <Link
                href="https://aniken.connpass.com/"
                target="_blank"
                className={styles["section__list-item-link"]}
              >
                アニメーション研究会
              </Link>
            </li>
            <li className={styles["section__list-item"]}>
              <Link
                href="https://ffs.connpass.com/"
                target="_blank"
                className={styles["section__list-item-link"]}
              >
                Frontend-Fukuoka.spec
              </Link>
            </li>
          </ul>
        </Section>
      </SectionContainer>
    </Container>
  );
}

// src/pages/About.vue
<template>
  <Layout>
    <PageHeading>About</PageHeading>

    <section class="About-Section">
      <h2 class="About-Section_Heading">Work</h2>

      <ul class="About-List">
        <li class="About-ListItem">
          Front-end Engineer: Linc'well - (December 2022 - Present)
        </li>

        <li class="About-ListItem">
          Front-end Engineer: HRBrain - (July 2020 - October 2022)
        </li>

        <li class="About-ListItem">
          Front-end Engineer: VEGA corporation - (July 2018 - June 2020)
        </li>

        <li class="About-ListItem">
          Web Designer: Japanese company - (2016 - June 2018)
        </li>
      </ul>
    </section>

    <section class="About-Section">
      <h2 class="About-Section_Heading">Internet</h2>

      <ul class="About-List">
        <li class="About-ListItem">
          <g-link
            href="https://twitter.com/tyankatsu5"
            class="About-ListItem_Link"
          >
            Twitter
          </g-link>
        </li>

        <li class="About-ListItem">
          <g-link
            href="https://github.com/tyankatsu0105"
            class="About-ListItem_Link"
          >
            GitHub
          </g-link>
        </li>

        <li class="About-ListItem">
          <g-link
            href="https://www.npmjs.com/~tyankatsu0105"
            class="About-ListItem_Link"
          >
            npm
          </g-link>
        </li>

        <li class="About-ListItem">
          <g-link
            href="https://speakerdeck.com/tyankatsu"
            class="About-ListItem_Link"
          >
            Speaker Deck
          </g-link>
        </li>

        <li class="About-ListItem">
          <g-link
            href="https://katsulog.netlify.app/"
            class="About-ListItem_Link"
          >
            katsulog(diary)
          </g-link>
        </li>
      </ul>
    </section>

    <section class="About-Section">
      <h2 class="About-Section_Heading">Book</h2>

      <ul class="About-List">
        <li class="About-ListItem">
          <g-link
            href="https://ponday.booth.pm/items/1316963"
            class="About-ListItem_Link"
          >
            チームマネジメントとGridsome／VuePress
          </g-link>
        </li>
      </ul>
    </section>

    <section class="About-Section">
      <h2 class="About-Section_Heading">Community</h2>

      <ul class="About-List">
        <li class="About-ListItem">
          <g-link
            href="https://aniken.connpass.com/"
            class="About-ListItem_Link"
          >
            アニメーション研究会
          </g-link>
        </li>

        <li class="About-ListItem">
          <g-link href="https://ffs.connpass.com/" class="About-ListItem_Link">
            Frontend-Fukuoka.spec
          </g-link>
        </li>

        <li class="About-ListItem">
          <g-link
            href="https://v-fukuoka.connpass.com/"
            class="About-ListItem_Link"
          >
            v-fukuoka
          </g-link>
        </li>

        <li class="About-ListItem">
          <g-link
            href="https://fec-fukuoka.connpass.com/"
            class="About-ListItem_Link"
          >
            フロントエンドカンファレンス福岡
          </g-link>
        </li>
      </ul>
    </section>

    <section class="About-Section">
      <h2 class="About-Section_Heading">Podcast</h2>

      <ul class="About-List">
        <li class="About-ListItem">
          <g-link
            href="https://spotifyanchor-web.app.link/e/LhoxDoIJKyb"
            class="About-ListItem_Link"
          >
            くつぬぎ、くつろぎ
          </g-link>
        </li>

        <li class="About-ListItem">
          <g-link href="https://anchor.fm/hrbrain" class="About-ListItem_Link">
            HRBrain ノウナイラジオ
          </g-link>
        </li>

        <li class="About-ListItem">
          <g-link
            href="https://anchor.fm/fukuokazatsudanradio"
            class="About-ListItem_Link"
          >
            ちょっとお隣よかですか？ - 福岡IT系雑談ラジオ
          </g-link>
        </li>
      </ul>
    </section>
  </Layout>
</template>

<script>
  import Layout from "~/layouts/Default.vue";
  import PageHeading from "~/ui/atoms/PageHeading.vue";
  import { meta } from "~/shared/meta";

  export default {
    components: {
      Layout,
      PageHeading,
    },

    metaInfo() {
      return meta({
        title: "About",
        url: `${process.env.GRIDSOME_APP_BASE_URL}/about`,
        description: `著者紹介ページです。`,
      });
    },
  };
</script>

<style lang="scss" scoped>
  .About {
    &-Section {
      & + & {
        margin-top: 12px;
      }
      &_Heading {
        font-size: 2rem;
        font-weight: bold;
      }
    }

    &-ListItem {
      font-weight: bold;
    }
  }
</style>
